services:
  - type: web
    name: iapply
    env: node
    region: singapore
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://iapply-telegram-bot.onrender.com
    buildFilter:
      paths:
        - client/**
        - shared/**
        - tsconfig.base.json
        - package.json
        - package-lock.json
      ignoredPaths:
        - server/**
        - ai-service/**
        - extension/**

  - type: web
    name: iapply-telegram-bot
    env: node
    region: oregon
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://iapply.onrender.com
      - key: APP_URL
        value: https://iapply-telegram-bot.onrender.com
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    buildFilter:
      paths:
        - server/**
        - shared/**
        - tsconfig.base.json
        - package.json
        - package-lock.json
      ignoredPaths:
        - client/**
        - ai-service/**
        - extension/**
